# Generated by Django 5.2.6 on 2025-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["country"], name="network_net_country_4e9322_idx"
            ),
        ),
    ]
